Parameters:
  # New Bucket name
  MyBucketName:
    Description: Existing Bucket name
    Type: String
    

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${MyBucketName}"
      # AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref 'WebsiteBucket'
      PolicyDocument:
        Statement:
        - Sid: PublicReadForGetBucketObjects
          Effect: Allow
          Principal: 
            AWS: 
              - '*'
          Action: 
            - s3:*
          Resource: !Join ['', ['arn:aws:s3:::', !Ref 'WebsiteBucket', /*]]